---
Gemfile:
  optional:
    ":development":
      - gem: beaker
        version: '~> 4.30'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.9'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 1.22'
      - gem: async
        version: '~> 1'
      - gem: beaker-module_install_helper
      - gem: beaker-puppet_install_helper
      - gem: nokogiri
    ":system_tests":
      - gem: voxpupuli-acceptance

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
# We still use the Vox acceptance Rake task instead of Litmus
Rakefile:
  requires:
    - require: voxpupuli/acceptance/rake
      conditional: Gem.loaded_specs.key? 'voxpupuli-acceptance'
